fail_fast: true
repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.0dev # Fill in a tag / sha here
    hooks:
      - id: gitlint
  - repo: git@github.com:dldinternet/b2b-project-lint.git
    rev: v0.2.2
    hooks:
      - id: b2blint

  - repo: https://github.com/dldinternet/gitown
    rev: v0.2.5
    hooks:
      - id: gitown
        args: [ '--ownership_threshold=10', '--codeowners_filename=CODEOWNERS' ]  # Optional
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
        exclude: ^(.devcontainer/.*)$
      - id: check-yaml
        exclude: ^(.github/.*)$
      - id: check-toml
        exclude: ^(\{\{cookiecutter.project_name\}\}/.*)$
      - id: end-of-file-fixer
        exclude: ^(requirements-dev.txt|requirements\.txt|.*\.history|CHANGELOG.md|runConfigurations/.*|.*\.iml)$
      - id: trailing-whitespace
        exclude: ^(pyproject.toml)$
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [ "--fix=lf" ]
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: [ "src/", "tests", "--extend-exclude=tests/samples/unit/user_rules/import_exception/invalid_python.py" ]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [ "--check" ]
  #      - id: poetry-export
  #        args: ["--with", "dev", "--without-hashes", "-f", "requirements.txt", "-o", "requirements-dev.txt"]
  #      - id: poetry-export
  #        args: ["--without-hashes", "-f", "requirements.txt", "-o", "requirements.txt"]
  - repo: local
    hooks:
      - id: pyproject-fmt
        name: Run poe pyproject-fmt
        language: system
        entry: poetry run poe pyproject-fmt
        always_run: true
        pass_filenames: false
      - id: lint
        name: Run poe lint
        language: system
        entry: poetry run poe lint
        always_run: true
        pass_filenames: false
